Fixed rbg percentage parsing in nsvg__parseColorRGB
memononen/nanosvg pull request #205
Opened 2022-04-07 01:54 UTC by AuthorityFX

2022-04-07 08:42 UTC, alerque approved these changes

2022-04-07 09:06 UTC, oehhar commented
Dear AuthorityFX,
thank you for the code, this is appreciated.
Your proposal is to allow float numbers in the RGB field instead of integers.
Do you have any rational for this?
Remark that a rationale may help the pull request to be merged.
Take care,
Harald

2022-04-07 12:32 UTC, AuthorityFX commented
> Dear AuthorityFX, thank you for the code, this is appreciated. Your proposal is to allow float numbers in the RGB field instead of integers. Do you have any rational for this? Remark that a rationale may help the pull request to be merged. Take care, Harald

https://lists.w3.org/Archives/Public/www-svg/2014Jan/0109.html

I'm using assets exported from Adobe InDesign.

Adobe InDesign exports rgb percentage as floats. SVGs from InDesign are handled correctly in other parsers.

2022-04-07 17:48 UTC, memononen requested changes

2022-04-07 17:48 UTC, memononen commented on src/nanosvg.h
> +	float rf=0, gf=0, bf=0;
definitions go to the top of the block (line after the r,g,b)

2022-04-07 21:57 UTC, merged

2022-04-07 21:59 UTC, memononen commented
@AuthorityFX Thanks for the fix, and thanks @oehhar for triage.

2022-04-08 08:46 UTC, oehhar commented
Thank you all for the action, I appreciate !